- src/test/java/seedu/duke/DukeTest.java
> PR from Sam

- src/main/java/seedu/duke/Duke.java
> Jovan testing PR

- text-ui-test/EXPECTED.TXT
Updated EXPECTED.TXT to match the ACTUAL.TXT
> Update the EXPECTED.TXT

- src/main/java/seedu/duke/Project.java
- src/main/java/seedu/duke/Resource.java
> Create Project and Resource classes

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/Project.java
- src/main/java/seedu/duke/Resource.java
- src/main/java/seedu/duke/command/CommandHandler.java
- src/test/java/seedu/duke/DukeTest.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
> [Sam] Added "add" functionality into Duke

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/CommandHandler.java
- text-ui-test/EXPECTED.TXT
- text-ui-test/input.txt
Changed all print -> println
Added a string to prompt user when resource is failed to be added
> [Sam] Minor updates on Duke

- src/main/java/seedu/duke/Duke.java
> Add help command

- src/main/java/seedu/duke/Duke.java
- text-ui-test/EXPECTED.TXT
> Refactor codes

- src/test/java/seedu/duke/DukeTest.java
Improve variable naming and cancel redundent variable.
Fixes #31
> Tp improve readability 1

- src/test/java/seedu/duke/ProjectTest.java
- src/test/java/seedu/duke/ResourceTest.java
> Add j unit test

- src/main/java/seedu/duke/Duke.java
> Add assert

- src/main/java/seedu/duke/Duke.java
> [Sam] add assert to ensure that projectInfo will not be null

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/CommandHandler.java
> Allow users to find the resources of a particular project.

- docs/DeveloperGuide.md
> Update Developer Guide for list-all & list PROJECTNAME feature.

- docs/DeveloperGuide.md
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/Project.java
- src/main/java/seedu/duke/parser/InputParser.java
- src/main/java/seedu/duke/resource/Resource.java
- src/main/java/seedu/duke/resource/ResourceManager.java
Added edit() function, but there is still a minor issue with it.
Added some parts of the developer guide.
> Fixes #49 

- src/main/java/seedu/duke/Duke.java
- src/test/java/seedu/duke/DukeTest.java
> Fix test for Find feature bug

- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/exception/InvalidArgumentException.java
- src/main/java/seedu/duke/parser/CommandParser.java
- src/main/java/seedu/duke/resource/Resource.java
- src/test/java/seedu/duke/DukeTest.java
- src/test/java/seedu/duke/ResourceTest.java
> [Sam] Added date feature to resource class and edited junit tests

- docs/DeveloperGuide.md
> [Sam] update Developer guide

- .gitignore
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/Project.java
- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/resource/Resource.java
- src/main/java/seedu/duke/storage/Storage.java
- src/main/java/seedu/duke/ui/MainUi.java
- src/test/java/seedu/duke/DukeTest.java
Saving and loading can be used by entering the commands "save" and "load" respectively.
Implemented this way because saving upon exit of program causes rest of JUnit tests to fail.
Updated "help" command and it's corresponding JUnit test.
Fixes #48
> Add save and load functionality

- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/exception/NoProjectNameException.java
- src/main/java/seedu/duke/exception/ProjectNotFoundException.java
> Refactor, reduce redundancy & added exceptions in list and list-all methods

- docs/UserGuide.md
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/parser/CommandParser.java
- src/main/java/seedu/duke/parser/InputParser.java
> [Sam] Updated UG

- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/ui/MainUi.java
- src/test/java/seedu/duke/DukeTest.java
- src/test/java/seedu/duke/command/CommandHandlerTest.java
> Add JUnit Test for List-all and list methods.

- docs/DeveloperGuide.md
> Update list-all and list's feature to developer guide.

- docs/UserGuide.md
> Update user guide for save and load

- docs/DeveloperGuide.md
> Update User Stories in Developer Guide (add list-all and list PROJECT NAME) stories

- docs/UserGuide.md
> Update user guide for list-all and list PROJECTNAME features.

- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/team/jovanhuang.md
> Fix minor bug in UserGuide.md

- src/main/java/seedu/duke/resource/Resource.java
- src/main/java/seedu/duke/storage/Storage.java
> Fix null description when loading project with no description

- src/main/java/seedu/duke/storage/Storage.java
Fixes #133 
Also fixes duplicate issues:
Closes #148, Closes #150, Closes #154, Closes #156
> Fix bug where projects are appended if load is called multiple time

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/parser/CommandParser.java
- src/main/java/seedu/duke/parser/InputParser.java
1. [PE-D] Entering space character in the beginning causes app to crash: Fixed by triming the input and checking if command is null before switch in processCommand()
2. [PE-D] Order of parameters matters when adding a new resource: Fixed by adding another position check method
3. [PE-D] weird naming of variable in parser/CommandParser: Fixed by changing the naming of variable
4. [PE-D] Same project name but different projects will be created: Fixed by trimming the information
5. [PE-D] Project Name With Space In The End: Same as 4
Fixes #149
Fixes #153
Fixes #142
Fixes #127
Fixes #128
> [Sam] Bug Fix

- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/project/ProjectManager.java
- src/main/java/seedu/duke/resource/Resource.java
- src/main/java/seedu/duke/resource/ResourceManager.java
- src/test/java/seedu/duke/DukeTest.java
Fixes #140 
Fixes #134 
Fixes #151
> Fixed bugs with Find

- src/main/java/seedu/duke/command/CommandHandler.java
Project will now be deleted if delete entire project
or all resources are deleted.
Fixes #129
> Fix bug where project is not deleted

- src/main/java/seedu/duke/resource/Resource.java
Fixes #131 
Fixes #141
Fixes #145
> Add finding for url of resource

- docs/UserGuide.md
- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/exception/InvalidArgumentException.java
- src/main/java/seedu/duke/parser/CommandParser.java
- src/test/java/seedu/duke/DukeTest.java
- src/test/java/seedu/duke/command/CommandHandlerTest.java
[PE-D] Certain wrong inputs manage to successfully create entry: Fixed
[PE-D] Invalid URLs accepted: Fixed, the user could choose whether to perform URL check which requires internet access by providing extra parameter c/true.
Fixes #137
Fixes #136
> [Sam] Fix bug related to command order and add junit tests

- docs/DeveloperGuide.md
> Add to instructions for manual testing

- src/main/java/seedu/duke/command/CommandHandler.java
- src/test/java/seedu/duke/resource/ResourceManagerTest.java
- src/test/java/seedu/duke/resource/ResourceTest.java
> Add JUnit Tests

- docs/UserGuide.md
- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/ui/MainUi.java
- src/test/java/seedu/duke/DukeTest.java
- src/test/java/seedu/duke/command/CommandHandlerTest.java
- text-ui-test/EXPECTED.TXT
> Update list feature to follow conventional format.

- docs/UserGuide.md
- src/main/java/seedu/duke/command/CommandHandler.java
- src/main/java/seedu/duke/project/ProjectManager.java
- src/main/java/seedu/duke/resource/ResourceManager.java
- src/main/java/seedu/duke/ui/MainUi.java
- src/test/java/seedu/duke/command/CommandHandlerTest.java
- src/test/java/seedu/duke/project/ProjectManagerTest.java
> Move list methods to Manager class.

- src/main/java/seedu/duke/command/CommandHandler.java
- src/test/java/seedu/duke/DukeTest.java
> Fix bug in DukeTest, testEditResource() and add loggings for list features.
